slogan: "浮世皆可斩，方戟穿世行；不染尘埃过，但求身正行。"

show_heart: true

show_slogan: true

menu:
  - title: Archives
    url: archives
    intro: "All the articles."
    icon: "fa fa-archive"
  - title: Categories
    url: categories
    intro: "All the categories."
    icon: "fa fa-folder"
  - title: Tags
    url: tags
    intro: "All the tags."
    icon: "fa fa-tags"
  - title: About
    url: about
    intro: "About me."
    icon: "fa fa-user"
  - title: RSS
    url: atom.xml
    intro: "Subscribe me."
    icon: "fa fa-user"

links:
  - title: "万山居士的Github"
    url: https://github.com/wanshansec
    intro: ""
    icon: "fa fa-github"

  # - title: "My LinkedIn"
  #   url: http://www.linkedin.com/in/xxx
  #   intro: "My Linkin account."
  #   icon: "fa fa-linkedin"

widgets:
- search
- category
- tagcloud
- recent_posts
- links

rss: 
fancybox: true
favicon: favicon.png
#duoshuo_shortname: 


# Analytics (change to yours)
google_analytics:
  enable: false
  siteid: 


# search
# swiftype_key: WTix4gy_FF5D5dTX2iih

#valine comment (change to yours)
valine:
  enable: false
  appId: 'xxx'
  appKey: 'xxx'
  placeholder: "提交评论时留下邮箱收到回复后将自动通知"
  visitor: false
  avatar: 'monsterid'
  requiredFields: ['nick','mail']
